apiVersion: v1
kind: Service
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  type: NodePort 
  selector:
    app: sunnybikes
  ports:
    - port: {{ .Values.sbservice.port }}
      targetPort: 5000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sunnybikes
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
